name: "Post Merge: Process Modified Notebook"
description: "Invoke script to process changes to a notebook"

inputs:
  modified_notebook:
    description: "The notebook that has changed"
    required: true
  PINECONE_API_KEY:
    description: "The Pinecone API key"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install nbformat requests pinecone

    - id: process-changes
      shell: bash
      name: Process changes to ${{ inputs.modified_notebook }}
      run: |
        python .github/actions/post-merge-modifications/process-modifications.py ${{ inputs.modified_notebook }}
      env:
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
