name: Check notebook structure
description: Validates notebook structure follows guidelines (intro, cleanup, imports)

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      shell: bash
      run: uv sync --only-group dev

    - name: Check notebook structure
      shell: bash
      run: uv run python ${{ github.action_path }}/check-structure.py
