name: Check for secrets
description: Scans notebooks for hardcoded API keys and secrets

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      shell: bash
      run: uv pip install nbformat --system

    - name: Check for secrets
      shell: bash
      run: python ${{ github.action_path }}/check-secrets.py
