name: "Run Notebook"
description: "Run a notebook"

inputs:
  notebook:
    description: "The notebook to run"
    required: true
  PINECONE_API_KEY:
    description: "The Pinecone API key"
    required: true
  OPENAI_API_KEY:
    description: "The OpenAI API key"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install nbformat

    - id: convert
      shell: bash
      name: Convert notebook into tmpdir script
      run: |
        python .github/actions/run-notebook/convert-notebook.py ${{ inputs.notebook }}
    
    - name: View the run script
      shell: bash
      run: |
        cat ${{ steps.convert.outputs.script_path }}

    - name: View converted notebook content
      shell: bash
      run: |
        cat ${{ steps.convert.outputs.notebook_path }}

    - name: Run the converted notebook
      shell: bash
      run: |
        bash ${{ steps.convert.outputs.script_path }}
      env:
        PINECONE_API_KEY: ${{ inputs.PINECONE_API_KEY }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}