{
 "title": "Pinecone Dashboard",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "IndexName", "query": { "query": "label_values(index_name)" } }
  ]
 },
 "panels": [
  { "title": "$IndexName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "IndexName" },
  {
   "title": "Current Pod Fullness",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(pinecone_index_fullness{index_name=\"$IndexName\"}[$__interval])",
     "legendFormat": "{{index_name}}"
    }
   ]
  },
  {
   "title": "Average Latency by Request Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(request_type) (pinecone_request_latency_seconds{index_name=\"$IndexName\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count by Request Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum by(request_type) (increase(pinecone_request_count_total{index_name=\"$IndexName\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate by Request Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(request_type) (increase(pinecone_request_error_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Fullness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(pinecone_index_fullness{index_name=\"$IndexName\"})",
     "legendFormat": "{{index_name}}"
    }
   ]
  },
  {
   "title": "Vector Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "pinecone_vector_count{index_name=\"$IndexName\"}",
     "legendFormat": "{{index_name}}"
    }
   ]
  }
 ]
}