name: "Pull Request"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  report-client-versions:
    uses: './.github/workflows/client-versions.yaml'
    secrets: inherit

  test-notebooks:
    uses: './.github/workflows/test-notebooks-changed.yaml'
    secrets: inherit
