name: "Test: Notebook Execution"

on:
  workflow_call:
    inputs:
      base_ref:
        required: false
        type: string
        default: 'master'

jobs:
  validate-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/validate-json

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      has_changes: ${{ steps.set-matrix.outputs.has_changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git diff

      - name: Fetch base branch
        run: git fetch origin ${{ inputs.base_ref }}

      - name: Detect changed notebooks
        id: set-matrix
        run: |
          # Get list of changed .ipynb files
          CHANGED_NOTEBOOKS=$(git diff --diff-filter=d --name-only origin/${{ inputs.base_ref }}...HEAD | grep '\.ipynb$' || true)
          if [ -z "$CHANGED_NOTEBOOKS" ]; then
            echo "No notebook changes detected"
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "matrix={\"notebook\":[]}" >> $GITHUB_OUTPUT
          else
            # Convert newlines to JSON array format
            NOTEBOOK_LIST=$(echo "$CHANGED_NOTEBOOKS" | jq -R -s -c 'split("\n")[:-1]')
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "matrix={\"notebook\":$NOTEBOOK_LIST}" >> $GITHUB_OUTPUT
          fi

  test-notebooks:
    needs: 
      - detect-changes
      - validate-notebooks
    if: needs.detect-changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.detect-changes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run-notebook
        with:
          notebook: ${{ matrix.notebook }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  check-links:
    needs:
      - validate-notebooks
      - detect-changes
    if: needs.detect-changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.detect-changes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-links
        with:
          notebook: ${{ matrix.notebook }}
