name: "Test: Notebook Execution"

on:
  workflow_dispatch: {}

jobs:
  test-notebooks:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            notebook:
                - learn/search/semantic-search/semantic-search.ipynb
                - docs/gen-qa-openai.ipynb
                - docs/langchain-retrieval-agent.ipynb
                - docs/langchain-retrieval-augmentation.ipynb
                - docs/pinecone-reranker.ipynb
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - id: convert
        name: Convest test notebook into tmpdir script
        run: |
          python .github/scripts/convert-notebook.py ${{ matrix.notebook }}
        
      - name: Run the converted notebook
        shell: bash
        run: |
          bash ${{ steps.convert.outputs.script_path }}
        env:
            PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
