name: Validate Notebook JSON

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install nbformat

      - name: Validate all notebooks
        run: |
          python .github/scripts/validate-notebook-formats.py